plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.5'
    id 'io.spring.dependency-management' version '1.1.6'
}
group='com.academix'; version='0.1.0'
java { toolchain { languageVersion=JavaLanguageVersion.of(21) } }
repositories { mavenCentral() }
dependencies {
 implementation 'org.springframework.boot:spring-boot-starter-web'
 implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
 implementation 'org.springframework.boot:spring-boot-starter-validation'
 implementation 'org.flywaydb:flyway-core'
 implementation 'org.hibernate.orm:hibernate-community-dialects'
 runtimeOnly 'org.xerial:sqlite-jdbc:3.46.1.0'
 implementation 'org.apache.poi:poi-ooxml:5.3.0'
 implementation 'com.opencsv:opencsv:5.9'
 compileOnly 'org.projectlombok:lombok'
 annotationProcessor 'org.projectlombok:lombok'
 testImplementation 'org.springframework.boot:spring-boot-starter-test'
 testImplementation 'org.springframework:spring-test'
 testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
tasks.named('test'){useJUnitPlatform()}
