import{useEffect,useState}from'react';
import{UploadCloud,Search,Filter,MoreHorizontal,RotateCcw}from'lucide-react';
import StudentTable from'../components/StudentTable';
import StatusBadge from'../components/StatusBadge';
import{getApiErrorMessage,getImports,getStudentFilterOptions,uploadStudents}from'../api';

const textAndRangeFields=[
 ['fullName','Name','text'],['phone','Phone','tel'],['email','Email','email'],['studentCode','Student ID','text'],
 ['ageFrom','Minimum age','number'],['ageTo','Maximum age','number'],
 ['admissionFrom','Admission from','date'],['admissionTo','Admission to','date']
];
const emptyOptions={courses:[],classes:[],states:[],cities:[],batches:[],statuses:[],sources:[]};
const dropdowns=[['course','Course','courses'],['className','Class','classes'],['state','State','states'],['city','City','cities'],['batch','Batch','batches'],['status','Status','statuses'],['source','Source','sources']];

export function StudentsPage({students,total,page,size,onPageChange,onPageSizeChange,loading,error,query,onQueryChange,filters,onFilterChange,onStateChange,onClear,sort,onSortChange,onExport}){
 const[showFilters,setShowFilters]=useState(true),[exporting,setExporting]=useState(false),[exportError,setExportError]=useState(''),[options,setOptions]=useState(emptyOptions),[optionsError,setOptionsError]=useState('');
 const activeCount=Object.values(filters).filter(Boolean).length+(query?1:0);
 useEffect(()=>{let current=true;setOptionsError('');getStudentFilterOptions(filters.state).then(value=>{if(current)setOptions(value)}).catch(e=>{if(current)setOptionsError(getApiErrorMessage(e))});return()=>{current=false}},[filters.state]);
 async function handleExport(){if(exporting)return;setExporting(true);setExportError('');try{await onExport()}catch(e){setExportError(getApiErrorMessage(e))}finally{setExporting(false)}}
 return <><div className="page-heading"><div><p className="eyebrow">STUDENT DIRECTORY</p><h1>Students</h1><p>Search, filter and manage all student records</p></div></div>
 <div className="filterbar"><div><Search size={18}/><input value={query} onChange={e=>onQueryChange(e.target.value)} placeholder="Search name, phone, email or student ID..."/></div><button className={showFilters?'filter-active':''} onClick={()=>setShowFilters(value=>!value)}><Filter size={16}/> Filters {activeCount>0&&<b>{activeCount}</b>}</button><select value={size} onChange={e=>onPageSizeChange(Number(e.target.value))}><option value="25">25 per page</option><option value="50">50 per page</option><option value="100">100 per page</option></select></div>
 {showFilters&&<section className="filter-panel"><div className="filter-grid">{textAndRangeFields.map(([name,label,type])=><label key={name}><span>{label}</span><input type={type} min={type==='number'?0:undefined} value={filters[name]} onChange={e=>onFilterChange(name,e.target.value)} placeholder={type==='text'||type==='email'||type==='tel'?label:undefined}/></label>)}{dropdowns.map(([name,label,key])=><label key={name}><span>{label}</span><select value={filters[name]} onChange={e=>name==='state'?onStateChange(e.target.value):onFilterChange(name,e.target.value)}><option value="">All {label==='Class'?'Classes':`${label}s`}</option>{options[key].map(value=><option key={value} value={value}>{value}</option>)}</select></label>)}<label><span>Sort results</span><select value={sort} onChange={e=>onSortChange(e.target.value)}><option value="createdAt:desc">Newest first</option><option value="createdAt:asc">Oldest first</option><option value="fullName:asc">Name A–Z</option><option value="fullName:desc">Name Z–A</option><option value="studentCode:asc">Student ID A–Z</option><option value="city:asc">City A–Z</option><option value="course:asc">Course A–Z</option><option value="admissionDate:desc">Latest admission</option></select></label></div>{optionsError&&<div className="api-error filter-options-error">Could not load filter choices: {optionsError}</div>}<div className="filter-footer"><span>{activeCount?`${activeCount} active search/filter${activeCount===1?'':'s'}`:'Showing all students'}</span><button onClick={onClear} disabled={!activeCount}><RotateCcw size={15}/> Clear all</button></div></section>}
 {exportError&&<div className="api-error export-error">CSV export failed: {exportError}</div>}
 <StudentTable students={students} total={total} page={page} size={size} onPageChange={onPageChange} loading={loading} error={error} onExport={handleExport} exporting={exporting}/></>}

export function ImportPage({onImported}){const[file,setFile]=useState();const[progress,setProgress]=useState(0);const[result,setResult]=useState();const[busy,setBusy]=useState(false);async function send(){if(!file||busy)return;setBusy(true);try{const imported=await uploadStudents(file,e=>setProgress(Math.round(e.loaded/e.total*100)));setResult(imported);if(onImported)onImported(imported)}catch(e){setResult({error:getApiErrorMessage(e)})}finally{setBusy(false)}}return <><div className="page-heading"><div><p className="eyebrow">DATA INGESTION</p><h1>Import Data</h1><p>Upload Excel or CSV student records securely</p></div></div><section className="upload-card"><div className="upload-zone"><UploadCloud size={36}/><h2>Drop your student file here</h2><p>Supports .xlsx, .xls and .csv files up to 100 MB</p><label>Select file<input type="file" accept=".csv,.xls,.xlsx" onChange={e=>{setFile(e.target.files[0]);setResult();setProgress(0)}}/></label>{file&&<div className="picked"><strong>{file.name}</strong><span>{(file.size/1024).toFixed(1)} KB</span></div>}</div>{file&&<><div className="progress"><i style={{width:progress+'%'}}/></div><button className="primary import-btn" disabled={busy} onClick={send}>{busy?'Importing…':'Start import'}</button></>}{result&&<div className={result.error?'result error':'result'}>{result.error||`${result.successRows} records imported successfully${result.duplicateRows?` · ${result.duplicateRows} duplicate`:''}`}</div>}</section></>}

export function ImportHistoryPage(){const[imports,setImports]=useState([]),[error,setError]=useState('');useEffect(()=>{getImports({page:0,size:100}).then(result=>setImports(result.content)).catch(e=>setError(getApiErrorMessage(e)))},[]);return <><div className="page-heading"><div><p className="eyebrow">DATA INGESTION</p><h1>Import History</h1><p>Review previous student data uploads</p></div></div><section className="history-card">{error&&<div className="api-error">{error}</div>}{!error&&imports.length===0&&<div className="table-message">No imports yet</div>}{imports.map(item=><div className="history-row" key={item.id}><div><strong>{item.fileName}</strong><span>{new Date(item.startedAt).toLocaleString('en-IN')}</span></div><span>{Number(item.totalRows).toLocaleString('en-IN')} rows</span><span>{Number(item.successRows).toLocaleString('en-IN')} imported</span><StatusBadge status={item.status}/></div>)}</section></>}

export function Placeholder({title}){return <><div className="page-heading"><div><p className="eyebrow">ACADEMIX</p><h1>{title}</h1><p>Manage {title.toLowerCase()} across your workspace</p></div></div><section className="empty-panel"><MoreHorizontal size={28}/><h2>{title}</h2><p>This section is not implemented yet. Its unavailable actions have been disabled elsewhere.</p></section></>}
